#!/bin/bash

mode=$1

	case "$mode" in
			 'copy')
			 	killall -9 XKICK_Certify_sv
				make copy
				;;
	         'all')
				/home/kicks/football/Table/loadtable
				/home/kicks/football/common/CLIENT_SHARE/download
				./version_maker
				make clean
				make
				;;
			*)
				./version_maker
				make
				;;
	esac


